### ISSUE TITLE
NPEx when attempting to tear down the Mojarra runtime

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/mojarra#4586]
On undeploying web app (with Faces (2.3.9) enabled) `NPEx` is thrown from https://github.com/eclipse-ee4j/mojarra/blob/e6dacbc83c348efa6067d20d85768c540bfa95d0/impl/src/main/java/com/sun/faces/application/applicationimpl/Version.java#L66 as apparently it's possible for `getBeanReference` to return `null` (happens in my case).

```
Jul 10, 2019 4:43:32 PM com.sun.faces.config.ConfigureListener contextDestroyed
SEVERE: Unexpected exception when attempting to tear down the Mojarra runtime
java.lang.NullPointerException
	at com.sun.faces.application.applicationimpl.Version.isJsf23(Version.java:66)
	at com.sun.faces.application.applicationimpl.InstanceFactory.createConverter(InstanceFactory.java:479)
	at com.sun.faces.application.ApplicationImpl.createConverter(ApplicationImpl.java:510)
	at javax.faces.application.ApplicationWrapper.createConverter(ApplicationWrapper.java:431)
	at org.primefaces.config.PrimeConfiguration.<init>(PrimeConfiguration.java:65)
	at org.primefaces.context.PrimeApplicationContext.<init>(PrimeApplicationContext.java:75)
	at org.primefaces.context.PrimeApplicationContext.getCurrentInstance(PrimeApplicationContext.java:167)
	at org.primefaces.webapp.PreDestroyApplicationEventListener.processEvent(PreDestroyApplicationEventListener.java:41)
	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:123)
	at com.sun.faces.application.applicationimpl.Events.processListeners(Events.java:253)
	at com.sun.faces.application.applicationimpl.Events.invokeListenersFor(Events.java:231)
	at com.sun.faces.application.applicationimpl.Events.publishEvent(Events.java:112)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:127)
	at javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:788)
	at com.sun.faces.config.ConfigureListener.contextDestroyed(ConfigureListener.java:345)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextDestroyed(ContextHandler.java:967)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextDestroyed(ServletContextHandler.java:566)
	at org.eclipse.jetty.server.handler.ContextHandler.stopContext(ContextHandler.java:944)
	at org.eclipse.jetty.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:376)
	at org.eclipse.jetty.webapp.WebAppContext.stopWebapp(WebAppContext.java:1503)
	at org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1467)
	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:1011)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:569)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.deploy.bindings.StandardStopper.processBinding(StandardStopper.java:44)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:510)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:470)
	at org.eclipse.jetty.deploy.DeploymentManager.removeApp(DeploymentManager.java:421)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileRemoved(ScanningAppProvider.java:199)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileRemoved(WebAppProvider.java:454)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileRemoved(ScanningAppProvider.java:77)
	at org.eclipse.jetty.util.Scanner.reportRemoval(Scanner.java:637)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:535)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
	at org.eclipse.jetty.util.Scanner$1.run(Scanner.java:329)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by tandraschko** [comment]
This special case is now fixed by PF: https://github.com/primefaces/primefaces/issues/4990

We initialized our ApplicationContext on shutdown if it wasn't initialized before.

**Comment by pzygielo** [comment]
@tandraschko - indeed - with current PF 7.1 (built from https://github.com/primefaces/primefaces/commit/d44d00d228a04b5cea11ca9461b92205941bb393) I have clean undeploy, thanks.

**Comment by arjantijms** [comment]
@tandraschko thx for the update!

**Comment by pzygielo** [comment]
Usage in PrimeFaces only exposed problem that still exists in this project. NPEx IMO, shall not be thrown, as it can and should be prevented by programmer.
Please consider reopening.
